### ISSUE TITLE
Garbage repo

### ISSUE THREAD

**Issue by stefanodvx** [Bbalduzz/phantomflix#2]
thank you for cloning my original FlixCrack without any permission even after removal. Btw it's very embarassing promoting L3 selling XDD

**Comment by Bbalduzz** [comment]
lol mate, I havent sell any key, I've given them out to the ones who asked,
I knew it was your script, but it was uploaded by some Mavrick (only copy existing) and It wasnt even working at all and clearly discontinued (last update was 2 years ago).
If you want to I can remove this repo with no problems at all, but please update your projects before coming at me.

**Comment by Cohvir** [comment]
Imbarazzante. Se lasci la tua repo pubblica chiunque può fare un fork e svilupparne la sua versione.
Potrei capire se la tua repo fosse ben mantenuta e questa fosse una copia identica spacciata per invenzione propria, ma non mi sembra il caso. Potevi evitare questa figura.
